# Designed to Clean / Standardize any Dataset into a standard format

In [3]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import calendar
import string
from string import punctuation
from itertools import chain
import os

from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score, f1_score

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import NMF, LatentDirichletAllocation, TruncatedSVD
from sklearn.feature_selection import SelectPercentile, chi2, f_regression, f_classif

from sklearn import svm
from sklearn.utils import shuffle

Process 1 just to see what it looks like

In [4]:
df = pd.read_csv('AllData/Merged Location Csvs/Arima_weather_data_2026-05-17.csv',encoding='latin-1', skip_blank_lines=True) #load the dataset
pd.options.mode.copy_on_write = True  # Set copy_on_write to True to avoid SettingWithCopyWarning

# Read and Understand the Dataset

In [5]:
df.info()   # Display the DataFrame information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9546 entries, 0 to 9545
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              9546 non-null   object
 1   datetime          9546 non-null   object
 2   tempmax           9546 non-null   float64
 3   tempmin           9546 non-null   float64
 4   temp              9546 non-null   float64
 5   feelslikemax      9546 non-null   float64
 6   feelslikemin      9546 non-null   float64
 7   feelslike         9546 non-null   float64
 8   dew               9546 non-null   float64
 9   humidity          9546 non-null   float64
 10  precip            7750 non-null   float64
 11  precipprob        9546 non-null   float64
 12  precipcover       9546 non-null   float64
 13  windspeed         9546 non-null   float64
 14  winddir           9545 non-null   float64
 15  sealevelpressure  9544 non-null   float64
 16  cloudcover        9546 non-null   float64
 17  visibility        9543 non-null   float64
 18  solarradiation    5927 non-null   float64
 19  solarenergy       5927 non-null   float64
 20  uvindex           5927 non-null   float64
 21  sunrise           9546 non-null   object
 22  sunset            9546 non-null   object
 23  moonphase         9546 non-null   float64
 24  conditions        9546 non-null   object
 25  description       9546 non-null   object
 26  icon              9546 non-null   object
 27  stations          9546 non-null   object
dtypes: float64(20), object(8)
memory usage: 2.0+ MB

In [6]:
df.shape   # Display the shape of the DataFrame

df.isna().sum()

name                   0
datetime               0
tempmax                0
tempmin                0
temp                   0
feelslikemax           0
feelslikemin           0
feelslike              0
dew                    0
humidity               0
precip              1796
precipprob             0
precipcover            0
windspeed              0
winddir                1
sealevelpressure       2
cloudcover             0
visibility             3
solarradiation      3619
solarenergy         3619
uvindex             3619
sunrise                0
sunset                 0
moonphase              0
conditions             0
description            0
icon                   0
stations               0
dtype: int64

In [7]:
df.head(10)   #shows the first 10 rows of the CSV to highlight what the data looks like

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarradiation,solarenergy,uvindex,sunrise,sunset,moonphase,conditions,description,icon,stations
0,"Arima, Trinidad, Trinidad And Tobago",2000-01-01,87.8,71.7,79.5,94.3,71.7,81.9,72.0,78.9,...,NaN,NaN,NaN,2000-01-01T06:23:08,2000-01-01T17:53:56,0.83,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
1,"Arima, Trinidad, Trinidad And Tobago",2000-01-02,87.9,71.4,78.2,96.1,71.4,80.5,72.5,83.6,...,NaN,NaN,NaN,2000-01-02T06:23:32,2000-01-02T17:54:29,0.86,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
2,"Arima, Trinidad, Trinidad And Tobago",2000-01-03,89.7,73.5,79.3,95.0,73.5,81.2,71.5,78.6,...,NaN,NaN,NaN,2000-01-03T06:23:55,2000-01-03T17:55:02,0.90,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
3,"Arima, Trinidad, Trinidad And Tobago",2000-01-04,84.3,71.3,76.1,89.8,71.3,77.2,70.9,84.9,...,NaN,NaN,NaN,2000-01-04T06:24:18,2000-01-04T17:55:34,0.93,Partially cloudy,Clearing in the afternoon.,partly-cloudy-day,"78962099999,78970099999,78961399999"
4,"Arima, Trinidad, Trinidad And Tobago",2000-01-05,81.2,73.1,76.0,86.7,73.1,76.3,73.8,93.1,...,NaN,NaN,NaN,2000-01-05T06:24:39,2000-01-05T17:56:07,0.96,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
5,"Arima, Trinidad, Trinidad And Tobago",2000-01-06,87.8,73.5,77.9,96.0,73.5,79.7,73.4,86.7,...,NaN,NaN,NaN,2000-01-06T06:25:00,2000-01-06T17:56:40,0.00,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
6,"Arima, Trinidad, Trinidad And Tobago",2000-01-07,87.4,73.5,77.3,92.8,73.5,78.4,71.5,83.4,...,NaN,NaN,NaN,2000-01-07T06:25:20,2000-01-07T17:57:12,0.03,Partially cloudy,Becoming cloudy in the afternoon.,partly-cloudy-day,"78962099999,78970099999,78961399999"
7,"Arima, Trinidad, Trinidad And Tobago",2000-01-08,87.9,72.8,79.7,92.9,72.8,81.6,70.6,75.8,...,NaN,NaN,NaN,2000-01-08T06:25:39,2000-01-08T17:57:45,0.07,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
8,"Arima, Trinidad, Trinidad And Tobago",2000-01-09,87.9,71.7,78.5,95.4,71.7,81.3,72.3,82.3,...,NaN,NaN,NaN,2000-01-09T06:25:58,2000-01-09T17:58:17,0.10,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
9,"Arima, Trinidad, Trinidad And Tobago",2000-01-10,88.4,73.5,79.6,95.6,73.5,82.0,71.9,78.9,...,NaN,NaN,NaN,2000-01-10T06:26:15,2000-01-10T17:58:49,0.14,Partially cloudy,Becoming cloudy in the afternoon.,partly-cloudy-day,"78962099999,78970099999,78961399999"

In [8]:
df.describe()   # Display summary statistics of the DataFrame

,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,precip,precipprob,precipcover,windspeed,winddir,sealevelpressure,cloudcover,visibility,solarradiation,solarenergy,uvindex,moonphase
count,9546.000000,9546.000000,9546.000000,9546.000000,9546.000000,9546.000000,9546.000000,9546.000000,7750.000000,9546.000000,9546.000000,9546.000000,9545.000000,9544.000000,9546.000000,9543.000000,5927.000000,5927.000000,5927.000000,9546.000000
mean,88.719715,74.846962,80.649382,97.269820,74.862131,84.050796,73.384025,79.957239,0.185447,51.288812,4.657111,15.400545,96.390791,1012.645233,56.568207,6.987624,221.115202,19.093757,7.770710,0.483617
std,2.900351,2.254003,1.962049,5.234968,2.309649,3.535017,2.479126,6.156568,0.446054,49.985700,8.383503,5.077232,31.697134,1.544365,18.598573,0.994795,55.726248,4.806966,1.667187,0.288777
min,71.700000,48.100000,71.000000,71.700000,48.100000,71.000000,62.100000,59.000000,0.000000,0.000000,0.000000,0.000000,0.500000,1006.000000,11.800000,2.700000,0.000000,0.000000,0.000000,0.000000
25%,87.600000,73.400000,79.300000,93.600000,73.400000,81.400000,71.700000,75.500000,0.000000,0.000000,0.000000,12.800000,77.500000,1011.600000,40.900000,6.400000,186.800000,16.150000,7.000000,0.250000
50%,89.500000,75.200000,80.700000,97.500000,75.200000,84.000000,73.900000,79.700000,0.016000,100.000000,4.170000,15.000000,97.100000,1012.700000,52.500000,6.800000,231.200000,20.000000,8.000000,0.500000
75%,91.200000,76.700000,82.100000,100.500000,76.700000,86.600000,75.300000,84.400000,0.159000,100.000000,8.330000,17.200000,108.100000,1013.700000,72.700000,7.500000,264.300000,22.800000,9.000000,0.750000
max,116.000000,80.600000,86.100000,127.000000,88.200000,96.800000,79.100000,99.100000,9.030000,100.000000,100.000000,160.000000,359.600000,1017.600000,98.600000,16.800000,384.800000,28.200000,10.000000,0.980000

In [9]:
df.isna()   # returns all Null values, where Null = true.

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarradiation,solarenergy,uvindex,sunrise,sunset,moonphase,conditions,description,icon,stations
0,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9541,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9542,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9543,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9544,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9545,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [10]:
for col in df.columns:   # Loop through each column in the DataFrame and Print the number of unique values in each column
    print(col,df[col].nunique())

name 2
datetime 9546
tempmax 157
tempmin 116
temp 126
feelslikemax 301
feelslikemin 129
feelslike 222
dew 149
humidity 345
precip 1013
precipprob 3
precipcover 25
windspeed 188
winddir 1201
sealevelpressure 103
cloudcover 742
visibility 97
solarradiation 1979
solarenergy 240
uvindex 11
sunrise 9546
sunset 9546
moonphase 96
conditions 6
description 43
icon 5
stations 40

# Basic Data Preprocessing

Sunrise / sunset data convereted to just only contain time in 24 hour format.
Icon / Station / wind direction / sea pressure data was removed as deemed unncessary.
Tempratures converted to C from F.
Onehat Encoding for Condition.
Season Categroy added, converting it to Wet and Dry.
Precip converted from Inches to MM.
name truncated to only location (example port of spain)

Convert Sunset/Sunrise time to seconds

In [11]:
def convert_date(df):

    df['sunset'] = df['sunset'].astype("string")  # Convert 'sunset' column to string type
    df['sunrise'] = df['sunrise'].astype("string")
    df.dtypes

    return df

Convert Date to a number rather than string to make it actually useful for once

In [12]:
def convert_time(df):

    df['sunset'] = pd.to_datetime(df['sunset'], errors='coerce').dt.hour * 3600 + \
                pd.to_datetime(df['sunset'], errors='coerce').dt.minute * 60 + \
                pd.to_datetime(df['sunset'], errors='coerce').dt.second

    df['sunrise'] = pd.to_datetime(df['sunrise'], errors='coerce').dt.hour * 3600 + \
                pd.to_datetime(df['sunrise'], errors='coerce').dt.minute * 60 + \
                pd.to_datetime(df['sunrise'], errors='coerce').dt.second
    
    return df

Replace Missing Values

In [13]:
df.apply(pd.isnull).sum()/df.shape[0]

name                0.000000
datetime            0.000000
tempmax             0.000000
tempmin             0.000000
temp                0.000000
feelslikemax        0.000000
feelslikemin        0.000000
feelslike           0.000000
dew                 0.000000
humidity            0.000000
precip              0.188142
precipprob          0.000000
precipcover         0.000000
windspeed           0.000000
winddir             0.000105
sealevelpressure    0.000210
cloudcover          0.000000
visibility          0.000314
solarradiation      0.379112
solarenergy         0.379112
uvindex             0.379112
sunrise             0.000000
sunset              0.000000
moonphase           0.000000
conditions          0.000000
description         0.000000
icon                0.000000
stations            0.000000
dtype: float64

In [14]:
df["precip"].value_counts() / df.shape[0]

precip
0.000    0.298135
0.004    0.022837
0.012    0.019904
0.039    0.019380
0.001    0.019066
           ...
0.736    0.000105
0.061    0.000105
1.058    0.000105
1.669    0.000105
0.208    0.000105
Name: count, Length: 1013, dtype: float64

In [15]:
def drop_unnecessary_columns(df):
    """
    Drops unnecessary columns from the DataFrame.
    """
    columns_to_drop = ['icon', 'stations', 'description', 'conditions','precipprob', 'uvindex', 'moonphase']
    df.drop(columns=columns_to_drop, inplace=True, errors='ignore')  # Use errors='ignore' to avoid KeyError if column doesn't exist
    return df



df.head(10)

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarradiation,solarenergy,uvindex,sunrise,sunset,moonphase,conditions,description,icon,stations
0,"Arima, Trinidad, Trinidad And Tobago",2000-01-01,87.8,71.7,79.5,94.3,71.7,81.9,72.0,78.9,...,NaN,NaN,NaN,2000-01-01T06:23:08,2000-01-01T17:53:56,0.83,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
1,"Arima, Trinidad, Trinidad And Tobago",2000-01-02,87.9,71.4,78.2,96.1,71.4,80.5,72.5,83.6,...,NaN,NaN,NaN,2000-01-02T06:23:32,2000-01-02T17:54:29,0.86,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
2,"Arima, Trinidad, Trinidad And Tobago",2000-01-03,89.7,73.5,79.3,95.0,73.5,81.2,71.5,78.6,...,NaN,NaN,NaN,2000-01-03T06:23:55,2000-01-03T17:55:02,0.90,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
3,"Arima, Trinidad, Trinidad And Tobago",2000-01-04,84.3,71.3,76.1,89.8,71.3,77.2,70.9,84.9,...,NaN,NaN,NaN,2000-01-04T06:24:18,2000-01-04T17:55:34,0.93,Partially cloudy,Clearing in the afternoon.,partly-cloudy-day,"78962099999,78970099999,78961399999"
4,"Arima, Trinidad, Trinidad And Tobago",2000-01-05,81.2,73.1,76.0,86.7,73.1,76.3,73.8,93.1,...,NaN,NaN,NaN,2000-01-05T06:24:39,2000-01-05T17:56:07,0.96,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
5,"Arima, Trinidad, Trinidad And Tobago",2000-01-06,87.8,73.5,77.9,96.0,73.5,79.7,73.4,86.7,...,NaN,NaN,NaN,2000-01-06T06:25:00,2000-01-06T17:56:40,0.00,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
6,"Arima, Trinidad, Trinidad And Tobago",2000-01-07,87.4,73.5,77.3,92.8,73.5,78.4,71.5,83.4,...,NaN,NaN,NaN,2000-01-07T06:25:20,2000-01-07T17:57:12,0.03,Partially cloudy,Becoming cloudy in the afternoon.,partly-cloudy-day,"78962099999,78970099999,78961399999"
7,"Arima, Trinidad, Trinidad And Tobago",2000-01-08,87.9,72.8,79.7,92.9,72.8,81.6,70.6,75.8,...,NaN,NaN,NaN,2000-01-08T06:25:39,2000-01-08T17:57:45,0.07,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
8,"Arima, Trinidad, Trinidad And Tobago",2000-01-09,87.9,71.7,78.5,95.4,71.7,81.3,72.3,82.3,...,NaN,NaN,NaN,2000-01-09T06:25:58,2000-01-09T17:58:17,0.10,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
9,"Arima, Trinidad, Trinidad And Tobago",2000-01-10,88.4,73.5,79.6,95.6,73.5,82.0,71.9,78.9,...,NaN,NaN,NaN,2000-01-10T06:26:15,2000-01-10T17:58:49,0.14,Partially cloudy,Becoming cloudy in the afternoon.,partly-cloudy-day,"78962099999,78970099999,78961399999"

Convert rain to mm

In [16]:
def backfill_missing_rain(df):

    df["datetime"] = pd.to_datetime(df["datetime"], format='mixed' ,dayfirst=True)   #concert date to a datetime object
    df["day"] = df["datetime"].dt.day
    df["month"] = df["datetime"].dt.month
    df["year"] = df["datetime"].dt.year
    ref_df = df.loc['01/0/2005':'31/12/2025']

    day_avg_precip = (ref_df[ref_df['precip'].notna()].groupby(['month', 'day'])['precip'].mean())
    missing_mask = (df.year <= 2004) & (df['precip'].isna())
    df.loc[missing_mask, 'precip'] = df[missing_mask].apply(lambda row: day_avg_precip.get((row['month'], row['day']), None),axis=1)

    df.drop(columns=['precipprob'], inplace=True)
   
    return df

In [17]:
def inches_to_mm(inches):
    return inches * 25.4


def convert_inches_to_mm(df):
    df['precip'] = df['precip'].apply(lambda x: pd.Series(inches_to_mm(x)))
    df.rename(columns={"windspeed": "windspeed mph"})

    return df

df.head(10)

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarradiation,solarenergy,uvindex,sunrise,sunset,moonphase,conditions,description,icon,stations
0,"Arima, Trinidad, Trinidad And Tobago",2000-01-01,87.8,71.7,79.5,94.3,71.7,81.9,72.0,78.9,...,NaN,NaN,NaN,2000-01-01T06:23:08,2000-01-01T17:53:56,0.83,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
1,"Arima, Trinidad, Trinidad And Tobago",2000-01-02,87.9,71.4,78.2,96.1,71.4,80.5,72.5,83.6,...,NaN,NaN,NaN,2000-01-02T06:23:32,2000-01-02T17:54:29,0.86,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
2,"Arima, Trinidad, Trinidad And Tobago",2000-01-03,89.7,73.5,79.3,95.0,73.5,81.2,71.5,78.6,...,NaN,NaN,NaN,2000-01-03T06:23:55,2000-01-03T17:55:02,0.90,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
3,"Arima, Trinidad, Trinidad And Tobago",2000-01-04,84.3,71.3,76.1,89.8,71.3,77.2,70.9,84.9,...,NaN,NaN,NaN,2000-01-04T06:24:18,2000-01-04T17:55:34,0.93,Partially cloudy,Clearing in the afternoon.,partly-cloudy-day,"78962099999,78970099999,78961399999"
4,"Arima, Trinidad, Trinidad And Tobago",2000-01-05,81.2,73.1,76.0,86.7,73.1,76.3,73.8,93.1,...,NaN,NaN,NaN,2000-01-05T06:24:39,2000-01-05T17:56:07,0.96,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
5,"Arima, Trinidad, Trinidad And Tobago",2000-01-06,87.8,73.5,77.9,96.0,73.5,79.7,73.4,86.7,...,NaN,NaN,NaN,2000-01-06T06:25:00,2000-01-06T17:56:40,0.00,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
6,"Arima, Trinidad, Trinidad And Tobago",2000-01-07,87.4,73.5,77.3,92.8,73.5,78.4,71.5,83.4,...,NaN,NaN,NaN,2000-01-07T06:25:20,2000-01-07T17:57:12,0.03,Partially cloudy,Becoming cloudy in the afternoon.,partly-cloudy-day,"78962099999,78970099999,78961399999"
7,"Arima, Trinidad, Trinidad And Tobago",2000-01-08,87.9,72.8,79.7,92.9,72.8,81.6,70.6,75.8,...,NaN,NaN,NaN,2000-01-08T06:25:39,2000-01-08T17:57:45,0.07,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
8,"Arima, Trinidad, Trinidad And Tobago",2000-01-09,87.9,71.7,78.5,95.4,71.7,81.3,72.3,82.3,...,NaN,NaN,NaN,2000-01-09T06:25:58,2000-01-09T17:58:17,0.10,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
9,"Arima, Trinidad, Trinidad And Tobago",2000-01-10,88.4,73.5,79.6,95.6,73.5,82.0,71.9,78.9,...,NaN,NaN,NaN,2000-01-10T06:26:15,2000-01-10T17:58:49,0.14,Partially cloudy,Becoming cloudy in the afternoon.,partly-cloudy-day,"78962099999,78970099999,78961399999"

Convert Degrees

In [18]:
def fahrenheit_to_celsius(fahrenheit):
    celsius = (fahrenheit - 32) * 5 / 9
    return round(celsius, 1)

def convert_temperatures(df):

    df[[ 'tempmax c']] = df ['tempmax'].apply(lambda x: pd.Series(fahrenheit_to_celsius(x)))
    df[[ 'tempmin c']] = df ['tempmin'].apply(lambda x: pd.Series(fahrenheit_to_celsius(x)))
    df[[ 'avgtemp c']] = df ['temp'].apply(lambda x: pd.Series(fahrenheit_to_celsius(x)))

    df[[ 'feelslikemax c']] = df ['feelslikemax'].apply(lambda x: pd.Series(fahrenheit_to_celsius(x)))
    df[[ 'feelslikemin c']] = df ['feelslikemin'].apply(lambda x: pd.Series(fahrenheit_to_celsius(x)))
    df[[ 'avgfeelsliketemp c']] = df ['feelslike'].apply(lambda x: pd.Series(fahrenheit_to_celsius(x)))

    df[[ 'dewpoint c']] = df ['dew'].apply(lambda x: pd.Series(fahrenheit_to_celsius(x)))

    df.drop(columns=['temp'],inplace=True)
    df.drop(columns=['tempmax'],inplace=True)
    df.drop(columns=['tempmin'],inplace=True)

    df.drop(columns=['feelslike'],inplace=True)
    df.drop(columns=['feelslikemax'],inplace=True)
    df.drop(columns=['feelslikemin'],inplace=True)
    df.drop(columns=['dew'],inplace=True)

    return df

df.head(10)

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarradiation,solarenergy,uvindex,sunrise,sunset,moonphase,conditions,description,icon,stations
0,"Arima, Trinidad, Trinidad And Tobago",2000-01-01,87.8,71.7,79.5,94.3,71.7,81.9,72.0,78.9,...,NaN,NaN,NaN,2000-01-01T06:23:08,2000-01-01T17:53:56,0.83,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
1,"Arima, Trinidad, Trinidad And Tobago",2000-01-02,87.9,71.4,78.2,96.1,71.4,80.5,72.5,83.6,...,NaN,NaN,NaN,2000-01-02T06:23:32,2000-01-02T17:54:29,0.86,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
2,"Arima, Trinidad, Trinidad And Tobago",2000-01-03,89.7,73.5,79.3,95.0,73.5,81.2,71.5,78.6,...,NaN,NaN,NaN,2000-01-03T06:23:55,2000-01-03T17:55:02,0.90,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
3,"Arima, Trinidad, Trinidad And Tobago",2000-01-04,84.3,71.3,76.1,89.8,71.3,77.2,70.9,84.9,...,NaN,NaN,NaN,2000-01-04T06:24:18,2000-01-04T17:55:34,0.93,Partially cloudy,Clearing in the afternoon.,partly-cloudy-day,"78962099999,78970099999,78961399999"
4,"Arima, Trinidad, Trinidad And Tobago",2000-01-05,81.2,73.1,76.0,86.7,73.1,76.3,73.8,93.1,...,NaN,NaN,NaN,2000-01-05T06:24:39,2000-01-05T17:56:07,0.96,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
5,"Arima, Trinidad, Trinidad And Tobago",2000-01-06,87.8,73.5,77.9,96.0,73.5,79.7,73.4,86.7,...,NaN,NaN,NaN,2000-01-06T06:25:00,2000-01-06T17:56:40,0.00,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
6,"Arima, Trinidad, Trinidad And Tobago",2000-01-07,87.4,73.5,77.3,92.8,73.5,78.4,71.5,83.4,...,NaN,NaN,NaN,2000-01-07T06:25:20,2000-01-07T17:57:12,0.03,Partially cloudy,Becoming cloudy in the afternoon.,partly-cloudy-day,"78962099999,78970099999,78961399999"
7,"Arima, Trinidad, Trinidad And Tobago",2000-01-08,87.9,72.8,79.7,92.9,72.8,81.6,70.6,75.8,...,NaN,NaN,NaN,2000-01-08T06:25:39,2000-01-08T17:57:45,0.07,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
8,"Arima, Trinidad, Trinidad And Tobago",2000-01-09,87.9,71.7,78.5,95.4,71.7,81.3,72.3,82.3,...,NaN,NaN,NaN,2000-01-09T06:25:58,2000-01-09T17:58:17,0.10,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"78962099999,78970099999,78961399999"
9,"Arima, Trinidad, Trinidad And Tobago",2000-01-10,88.4,73.5,79.6,95.6,73.5,82.0,71.9,78.9,...,NaN,NaN,NaN,2000-01-10T06:26:15,2000-01-10T17:58:49,0.14,Partially cloudy,Becoming cloudy in the afternoon.,partly-cloudy-day,"78962099999,78970099999,78961399999"

In [19]:
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)  # Ignore FutureWarnings

def fill_missing_values(df):
    """
    Fill missing values in the DataFrame.
    """
    df = df.fillna(method="ffill")

    return df

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9546 entries, 0 to 9545
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              9546 non-null   object
 1   datetime          9546 non-null   object
 2   tempmax           9546 non-null   float64
 3   tempmin           9546 non-null   float64
 4   temp              9546 non-null   float64
 5   feelslikemax      9546 non-null   float64
 6   feelslikemin      9546 non-null   float64
 7   feelslike         9546 non-null   float64
 8   dew               9546 non-null   float64
 9   humidity          9546 non-null   float64
 10  precip            7750 non-null   float64
 11  precipprob        9546 non-null   float64
 12  precipcover       9546 non-null   float64
 13  windspeed         9546 non-null   float64
 14  winddir           9545 non-null   float64
 15  sealevelpressure  9544 non-null   float64
 16  cloudcover        9546 non-null   float64
 17  visibility        9543 non-null   float64
 18  solarradiation    5927 non-null   float64
 19  solarenergy       5927 non-null   float64
 20  uvindex           5927 non-null   float64
 21  sunrise           9546 non-null   object
 22  sunset            9546 non-null   object
 23  moonphase         9546 non-null   float64
 24  conditions        9546 non-null   object
 25  description       9546 non-null   object
 26  icon              9546 non-null   object
 27  stations          9546 non-null   object
dtypes: float64(20), object(8)
memory usage: 2.0+ MB

In [21]:
for col in df.columns:
    print(col,df[col].nunique())

name 2
datetime 9546
tempmax 157
tempmin 116
temp 126
feelslikemax 301
feelslikemin 129
feelslike 222
dew 149
humidity 345
precip 1013
precipprob 3
precipcover 25
windspeed 188
winddir 1201
sealevelpressure 103
cloudcover 742
visibility 97
solarradiation 1979
solarenergy 240
uvindex 11
sunrise 9546
sunset 9546
moonphase 96
conditions 6
description 43
icon 5
stations 40

In [22]:
df.isna().sum()

name                   0
datetime               0
tempmax                0
tempmin                0
temp                   0
feelslikemax           0
feelslikemin           0
feelslike              0
dew                    0
humidity               0
precip              1796
precipprob             0
precipcover            0
windspeed              0
winddir                1
sealevelpressure       2
cloudcover             0
visibility             3
solarradiation      3619
solarenergy         3619
uvindex             3619
sunrise                0
sunset                 0
moonphase              0
conditions             0
description            0
icon                   0
stations               0
dtype: int64

# Outlier Temprature Analysis
Max Temp Ever Recorded in Triniad : 37.8
Lowest Temp Ever Recorded in Trinidad : 16.1

https://www.metoffice.gov.tt/Climate#:~:text=The%20coolest%20minimum%20temperature%20is,and%2030th%2C%201964%20at%20Piarco.

Backfill null values with avg for that day to avoid squewing data

In [23]:
def backfill_solar_energy(df):
    

    # Calculate daily average solar energy using data from 2010 and after
    day_avg_solarenergy = df[df['year'] >= 2010].groupby(['month', 'day'])['solarenergy'].mean()

    # Mask: rows where solarenergy is null AND year is before 2010
    mask = df['solarenergy'].isna() & (df['year'] < 2010)

    # Replace those values with the daily average from 2010 and after
    df.loc[mask, 'solarenergy'] = df[mask].apply(
        lambda row: day_avg_solarenergy.get((row['month'], row['day']), row['solarenergy']),
        axis=1
    )

    return df

In [24]:
def backfill_solarradiation(df):
    
    """
    Fill missing solar radiation values using daily averages from 2010 and after.
    """

    # Calculate daily average solar energy using data from 2010 and after
    day_avg_solarradiation = df[df['year'] >= 2010].groupby(['month', 'day'])['solarradiation'].mean()

    # Mask: rows where solarenergy is null AND year is before 2010
    mask = df['solarradiation'].isna() & (df['year'] < 2010)

    # Replace those values with the daily average from 2010 and after
    df.loc[mask, 'solarradiation'] = df[mask].apply(
        lambda row: day_avg_solarradiation.get((row['month'], row['day']), row['solarradiation']),
        axis=1
    )
    return df

Replace outliers with more than 36C actual temp with average for that day

In [25]:
def fix_max_temps(df):
    """
    Fix maximum temperatures that are above 37.8 degrees Celsius.
    Replace them with the average maximum temperature for that day across all years.
    """

    # Calculate daily average max temperature for days where tempmax c <= 37.8

    day_avg_tempmax = df[df['tempmax c'] <= 37.8].groupby(['month', 'day'])['tempmax c'].mean()

    mask = df['tempmax c'] > 37.8

    df.loc[mask, 'tempmax c'] = df[mask].apply(
        lambda row: day_avg_tempmax.get((row['month'], row['day']), row['tempmax c']),
        axis=1
    )

    return df

Replace outlier mintemp < 16.1 with average for that day

In [26]:
def fix_min_temps(df):
    """
    Fix minimum temperatures that are below 16.1 degrees Celsius.
    Replace them with the average minimum temperature for that day across all years.
    """

    # Calculate daily average min temperature for days where tempmin c >= 16.1  

    day_avg_tempmin = df[df['tempmin c'] >= 16.1].groupby(['month', 'day'])['tempmin c'].mean()

    mask = df['tempmin c'] < 16.1

    df.loc[mask, 'tempmin c'] = df[mask].apply(
        lambda row: day_avg_tempmin.get((row['month'], row['day']), row['tempmin c']),
        axis=1
    )

    return df

# Replace outlier feelsmintemp < 16.1 with average for that day

In [27]:
def fix_feelslike_max(df):
    """
    Fix maximum feels-like temperatures that are above 37.8 degrees Celsius.
    Replace them with the average maximum feels-like temperature for that day across all years.
    """


    day_avg_tempminfeellike = df[df['feelslikemin c'] >= 16.1].groupby(['month', 'day'])['feelslikemin c'].mean()

    mask = df['feelslikemin c'] < 16.1

    df.loc[mask, 'feelslikemin c'] = df[mask].apply(
        lambda row: day_avg_tempminfeellike.get((row['month'], row['day']), row['feelslikemin c']),
        axis=1
    )
    df.drop(columns=['month', 'day', 'year'], inplace=True)

    return df

In [28]:

# Ensure 'datetime' column is a datetime type

def convert_datetime(df):
    """
    Convert the 'datetime' column to a datetime type and filter out rows before 2005.
    """
    
    # Convert 'datetime' column to datetime type
    df['datetime'] = pd.to_datetime(df['datetime'], errors='coerce')

    # Filter out rows before 2005
    df = df[df['datetime'] >= '2005-01-01']

    return df

In [29]:
def rename_all_columns():
    df['name'] = df['name'].apply(lambda x: x.split(',')[0].strip())
    location = df['name'].iloc[0]

    return location


def save_cleaned_data(df):

    # Run function and save cleaned file
    location = rename_all_columns()

    path ='Refined Datasets/'   # Define the path where the cleaned file will be saved
    oldfname = f'{path} {location} cleaned.csv'  # Check if the old file exists and remove it

    if os.path.exists(oldfname):
        os.remove(oldfname)   # Remove the old file if it exists

    fname = f'{path}{location} cleaned.csv'    #Append the location to the filename
    print(f"Saving cleaned {location} data to {path}")  
    df.to_csv(fname, index=False)   # Save the cleaned DataFrame to a CSV file
    print(f"Cleaned data saved to {fname}")   # Print a message indicating where the cleaned data is saved

In [30]:
location_csvs = []
refined_datasets_path = 'Refined Datasets/'  # Define the path for refined datasets
refined_datasets = []

# Create a report file to log the CSV files found in the directory
if not os.path.exists('Refined Datasets/report.txt'):
    report_file = open('Refined Datasets/report.txt', 'x')
else:
    report_file = open('Refined Datasets/report.txt', 'w')


report_file.write("Report of CSV files found in the directory:\n")


# Walk through the directory and collect all CSV files

for dirname, _, filenames in os.walk('AllData/Merged Location Csvs'):
    for filename in filenames:
        if filename.endswith('.csv'):
            location_csvs.append((dirname, filename))

            print(os.path.join(dirname, filename))

print(f"Found {len(location_csvs)} CSV files in the directory.")


for location in location_csvs:
    print(f"Processing {location[1]} in {location[0]}")
    df = pd.read_csv(os.path.join(location[0], location[1]), encoding='latin-1', skip_blank_lines=True)  # Load the dataset
    pd.options.mode.copy_on_write = True  # Set copy_on_write to True to avoid SettingWithCopyWarning

    df = convert_date(df)
    df = convert_time(df)
    df = backfill_missing_rain(df)
    df = convert_inches_to_mm(df)
    df = convert_temperatures(df)
    df = fill_missing_values(df)
    df = backfill_solar_energy(df)
    df = backfill_solarradiation(df)
    df = fix_max_temps(df)
    df = fix_min_temps(df)
    df = fix_feelslike_max(df)
    df = convert_datetime(df)
    df = drop_unnecessary_columns(df)


    save_cleaned_data(df)  # Save the cleaned DataFrame to a CSV file
    refined_datasets.append(df)  # Append the cleaned DataFrame to the list of refined datasets

    print(f"Finished processing {location[1]} in {location[0]}")
    report_file.write(f"Processed {location[1]} in {location[0]}\n")  # Log the processed file in the report
    df_report= df.isna().sum()
    report_file.write(f"Missing values report:\n{df_report}\n")  # Log the missing values report in the report file
    report_file.write("------------------------------------------------\n")  # Add a newline for better readability in the report file



report_file.close()  # Close the report file after processing all CSV files
print("All CSV files processed and report generated.")

AllData/Merged Location Csvs\Arima_weather_data_2026-05-17.csv
AllData/Merged Location Csvs\Chaguanas_weather_data_2026-05-17.csv
AllData/Merged Location Csvs\Couva-Tabaquite-Talparo_weather_data_2026-05-17.csv
AllData/Merged Location Csvs\Crown-Point_weather_data_2026-05-17.csv
AllData/Merged Location Csvs\Diego-Martin_weather_data_2026-05-17.csv
AllData/Merged Location Csvs\Penal-Debe_weather_data_2026-05-17.csv
AllData/Merged Location Csvs\Point-Fortin_weather_data_2026-05-17.csv
AllData/Merged Location Csvs\Port-of-Spain_weather_data_2026-05-17.csv
AllData/Merged Location Csvs\Princes-Town_weather_data_2026-05-17.csv
AllData/Merged Location Csvs\Rio-Claro-Mayaro_weather_data_2026-05-17.csv
AllData/Merged Location Csvs\San-Fernando_weather_data_2026-05-17.csv
AllData/Merged Location Csvs\San-Juan-Laventille_weather_data_2026-05-17.csv
AllData/Merged Location Csvs\Sangre-Grande_weather_data_2026-05-17.csv
AllData/Merged Location Csvs\Scarborough_weather_data_2026-05-17.csv
AllData/Merged Location Csvs\Siparia_weather_data_2026-05-17.csv
AllData/Merged Location Csvs\Tunapuna-Piarco_weather_data_2026-05-17.csv
Found 16 CSV files in the directory.
Processing Arima_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Saving cleaned Arima data to Refined Datasets/
Cleaned data saved to Refined Datasets/Arima cleaned.csv
Finished processing Arima_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Processing Chaguanas_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Saving cleaned Chaguanas data to Refined Datasets/
Cleaned data saved to Refined Datasets/Chaguanas cleaned.csv
Finished processing Chaguanas_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Processing Couva-Tabaquite-Talparo_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Saving cleaned Couva-Tabaquite-Taiparo data to Refined Datasets/
Cleaned data saved to Refined Datasets/Couva-Tabaquite-Taiparo cleaned.csv
Finished processing Couva-Tabaquite-Talparo_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Processing Crown-Point_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Saving cleaned Crown Point data to Refined Datasets/
Cleaned data saved to Refined Datasets/Crown Point cleaned.csv
Finished processing Crown-Point_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Processing Diego-Martin_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Saving cleaned Diego Martin data to Refined Datasets/
Cleaned data saved to Refined Datasets/Diego Martin cleaned.csv
Finished processing Diego-Martin_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Processing Penal-Debe_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Saving cleaned Penal-Debe data to Refined Datasets/
Cleaned data saved to Refined Datasets/Penal-Debe cleaned.csv
Finished processing Penal-Debe_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Processing Point-Fortin_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Saving cleaned Point Fortin data to Refined Datasets/
Cleaned data saved to Refined Datasets/Point Fortin cleaned.csv
Finished processing Point-Fortin_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Processing Port-of-Spain_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Saving cleaned Port of Spain data to Refined Datasets/
Cleaned data saved to Refined Datasets/Port of Spain cleaned.csv
Finished processing Port-of-Spain_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Processing Princes-Town_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Saving cleaned Princes Town data to Refined Datasets/
Cleaned data saved to Refined Datasets/Princes Town cleaned.csv
Finished processing Princes-Town_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Processing Rio-Claro-Mayaro_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Saving cleaned Rio Claro-Mayaro data to Refined Datasets/
Cleaned data saved to Refined Datasets/Rio Claro-Mayaro cleaned.csv
Finished processing Rio-Claro-Mayaro_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Processing San-Fernando_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Saving cleaned San Fernando data to Refined Datasets/
Cleaned data saved to Refined Datasets/San Fernando cleaned.csv
Finished processing San-Fernando_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Processing San-Juan-Laventille_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Saving cleaned San Juan-Laventille data to Refined Datasets/
Cleaned data saved to Refined Datasets/San Juan-Laventille cleaned.csv
Finished processing San-Juan-Laventille_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Processing Sangre-Grande_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Saving cleaned Sangre Grande data to Refined Datasets/
Cleaned data saved to Refined Datasets/Sangre Grande cleaned.csv
Finished processing Sangre-Grande_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Processing Scarborough_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Saving cleaned Scarborough data to Refined Datasets/
Cleaned data saved to Refined Datasets/Scarborough cleaned.csv
Finished processing Scarborough_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Processing Siparia_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Saving cleaned Siparia data to Refined Datasets/
Cleaned data saved to Refined Datasets/Siparia cleaned.csv
Finished processing Siparia_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Processing Tunapuna-Piarco_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
Saving cleaned Piarco data to Refined Datasets/
Cleaned data saved to Refined Datasets/Piarco cleaned.csv
Finished processing Tunapuna-Piarco_weather_data_2026-05-17.csv in AllData/Merged Location Csvs
All CSV files processed and report generated.

In [31]:
#concat all the cleaned data into one file

df = pd.concat(refined_datasets, ignore_index=True)  # Concatenate all cleaned DataFrames into one
df.to_csv('Refined Datasets/All_Cleaned_Data.csv', index=False)
print("All cleaned data concatenated and saved to 'Refined Datasets/All_Cleaned_Data.csv'.")

All cleaned data concatenated and saved to 'Refined Datasets/All_Cleaned_Data.csv'.