# Designed to Clean / Standardize any Dataset into a standard format

In [30]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import calendar
import string
from string import punctuation
from itertools import chain
import os

from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score, f1_score

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import NMF, LatentDirichletAllocation, TruncatedSVD
from sklearn.feature_selection import SelectPercentile, chi2, f_regression, f_classif

from sklearn import svm
from sklearn.utils import shuffle

Process 1 just to see what it looks like

In [ ]:
df = pd.read_csv('AllData/Merged Location Csvs/Chaguanas_weather_data_2000_2025.csv',encoding='latin-1', skip_blank_lines=True) #load the dataset
pd.options.mode.copy_on_write = True  # Set copy_on_write to True to avoid SettingWithCopyWarning

# Read and Understand the Dataset

In [32]:
df.info()   # Display the DataFrame information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9216 entries, 0 to 9215
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              9216 non-null   object
 1   datetime          9216 non-null   object
 2   tempmax           9216 non-null   float64
 3   tempmin           9216 non-null   float64
 4   temp              9216 non-null   float64
 5   feelslikemax      9216 non-null   float64
 6   feelslikemin      9216 non-null   float64
 7   feelslike         9216 non-null   float64
 8   dew               9216 non-null   float64
 9   humidity          9216 non-null   float64
 10  precip            7420 non-null   float64
 11  precipprob        9216 non-null   int64
 12  precipcover       9216 non-null   float64
 13  windspeed         9216 non-null   float64
 14  winddir           9186 non-null   float64
 15  sealevelpressure  8934 non-null   float64
 16  cloudcover        9216 non-null   float64
 17  visibility        9213 non-null   float64
 18  solarradiation    5597 non-null   float64
 19  solarenergy       5597 non-null   float64
 20  uvindex           5597 non-null   float64
 21  sunrise           9216 non-null   object
 22  sunset            9216 non-null   object
 23  moonphase         9216 non-null   float64
 24  conditions        9216 non-null   object
 25  description       9216 non-null   object
 26  icon              9216 non-null   object
 27  stations          9216 non-null   object
dtypes: float64(19), int64(1), object(8)
memory usage: 2.0+ MB

In [33]:
df.shape   # Display the shape of the DataFrame

df.isna().sum()

name                   0
datetime               0
tempmax                0
tempmin                0
temp                   0
feelslikemax           0
feelslikemin           0
feelslike              0
dew                    0
humidity               0
precip              1796
precipprob             0
precipcover            0
windspeed              0
winddir               30
sealevelpressure     282
cloudcover             0
visibility             3
solarradiation      3619
solarenergy         3619
uvindex             3619
sunrise                0
sunset                 0
moonphase              0
conditions             0
description            0
icon                   0
stations               0
dtype: int64

In [34]:
df.head(10)   #shows the first 10 rows of the CSV to highlight what the data looks like

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarradiation,solarenergy,uvindex,sunrise,sunset,moonphase,conditions,description,icon,stations
0,"Chaguanas, Trinidad, Trinidad And Tobago",01/01/2000,87.9,71.7,80.0,94.4,71.7,82.7,72.0,78.0,...,NaN,NaN,NaN,2000-01-01T06:23:33,2000-01-01T17:54:34,0.83,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
1,"Chaguanas, Trinidad, Trinidad And Tobago",02/01/2000,87.9,71.3,78.2,96.1,71.3,80.5,72.5,83.7,...,NaN,NaN,NaN,2000-01-02T06:23:56,2000-01-02T17:55:07,0.86,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
2,"Chaguanas, Trinidad, Trinidad And Tobago",03/01/2000,89.7,73.5,79.3,95.0,73.5,81.2,71.6,78.6,...,NaN,NaN,NaN,2000-01-03T06:24:20,2000-01-03T17:55:40,0.90,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
3,"Chaguanas, Trinidad, Trinidad And Tobago",04/01/2000,84.3,71.3,76.1,89.8,71.3,77.2,70.9,84.9,...,NaN,NaN,NaN,2000-01-04T06:24:42,2000-01-04T17:56:12,0.93,Partially cloudy,Clearing in the afternoon.,partly-cloudy-day,78970099999
4,"Chaguanas, Trinidad, Trinidad And Tobago",05/01/2000,81.2,73.1,76.1,86.7,73.1,76.5,73.9,93.0,...,NaN,NaN,NaN,2000-01-05T06:25:04,2000-01-05T17:56:45,0.96,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
5,"Chaguanas, Trinidad, Trinidad And Tobago",06/01/2000,87.9,73.5,77.9,96.1,73.5,79.7,73.4,86.7,...,NaN,NaN,NaN,2000-01-06T06:25:25,2000-01-06T17:57:18,0.00,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
6,"Chaguanas, Trinidad, Trinidad And Tobago",07/01/2000,87.5,73.5,77.3,92.9,73.5,78.4,71.5,83.4,...,NaN,NaN,NaN,2000-01-07T06:25:45,2000-01-07T17:57:50,0.03,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
7,"Chaguanas, Trinidad, Trinidad And Tobago",08/01/2000,87.9,72.8,79.7,92.9,72.8,81.6,70.6,75.8,...,NaN,NaN,NaN,2000-01-08T06:26:04,2000-01-08T17:58:22,0.07,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
8,"Chaguanas, Trinidad, Trinidad And Tobago",09/01/2000,87.9,71.7,78.5,95.4,71.7,81.3,72.3,82.3,...,NaN,NaN,NaN,2000-01-09T06:26:23,2000-01-09T17:58:55,0.10,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
9,"Chaguanas, Trinidad, Trinidad And Tobago",10/01/2000,88.4,73.5,79.6,95.7,73.5,82.0,71.9,78.8,...,NaN,NaN,NaN,2000-01-10T06:26:40,2000-01-10T17:59:27,0.14,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999

In [35]:
df.describe()   # Display summary statistics of the DataFrame

,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,precip,precipprob,precipcover,windspeed,winddir,sealevelpressure,cloudcover,visibility,solarradiation,solarenergy,uvindex,moonphase
count,9216.000000,9216.000000,9216.000000,9216.000000,9216.000000,9216.000000,9216.000000,9216.000000,7420.000000,9216.000000,9216.000000,9216.000000,9186.000000,8934.000000,9216.000000,9213.000000,5597.000000,5597.000000,5597.000000,9216.000000
mean,88.830827,74.802648,80.666667,97.361003,74.818218,84.069390,73.381174,79.946832,0.185646,45.865885,4.857348,15.207118,95.893033,1012.587620,58.408203,7.176359,219.639861,18.968698,7.712346,0.483228
std,2.961867,2.302414,1.978656,5.231379,2.358029,3.541462,2.453970,6.148005,0.443809,49.831501,12.565587,5.007551,32.097918,1.529799,17.982966,1.032494,55.851473,4.821172,1.673965,0.288573
min,71.700000,37.300000,71.000000,71.700000,37.300000,71.000000,62.100000,57.200000,0.000000,0.000000,0.000000,0.000000,0.100000,1006.000000,16.500000,2.700000,0.000000,0.000000,0.000000,0.000000
25%,87.700000,73.400000,79.300000,93.700000,73.400000,81.400000,71.700000,75.500000,0.000000,0.000000,0.000000,12.800000,76.400000,1011.600000,43.500000,6.600000,184.500000,15.900000,7.000000,0.250000
50%,89.600000,75.200000,80.700000,97.550000,75.200000,84.000000,73.900000,79.600000,0.012000,0.000000,0.000000,15.000000,96.400000,1012.700000,55.000000,7.100000,230.000000,19.900000,8.000000,0.500000
75%,91.300000,76.700000,82.200000,100.600000,76.700000,86.600000,75.300000,84.300000,0.161000,100.000000,4.170000,17.200000,108.000000,1013.700000,73.800000,7.700000,263.200000,22.700000,9.000000,0.750000
max,138.100000,80.600000,86.200000,138.100000,88.200000,96.800000,79.100000,99.300000,9.134000,100.000000,100.000000,162.400000,360.000000,1017.600000,100.000000,16.800000,328.700000,28.200000,10.000000,0.980000

In [36]:
df.isna()   # returns all Null values, where Null = true.

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarradiation,solarenergy,uvindex,sunrise,sunset,moonphase,conditions,description,icon,stations
0,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9211,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9212,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9213,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9214,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9215,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [37]:
for col in df.columns:   # Loop through each column in the DataFrame and Print the number of unique values in each column
    print(col,df[col].nunique())

name 1
datetime 9216
tempmax 143
tempmin 107
temp 123
feelslikemax 303
feelslikemin 121
feelslike 220
dew 149
humidity 342
precip 659
precipprob 2
precipcover 25
windspeed 133
winddir 1202
sealevelpressure 102
cloudcover 716
visibility 102
solarradiation 1981
solarenergy 241
uvindex 11
sunrise 9216
sunset 9216
moonphase 96
conditions 5
description 32
icon 5
stations 19

# Basic Data Preprocessing

Sunrise / sunset data convereted to just only contain time in 24 hour format.
Icon / Station / wind direction / sea pressure data was removed as deemed unncessary.
Tempratures converted to C from F.
Onehat Encoding for Condition.
Season Categroy added, converting it to Wet and Dry.
Precip converted from Inches to MM.
name truncated to only location (example port of spain)

Convert Sunset/Sunrise time to seconds

In [38]:
def convert_date(df):

    df['sunset'] = df['sunset'].astype("string")  # Convert 'sunset' column to string type
    df['sunrise'] = df['sunrise'].astype("string")
    df.dtypes

    return df

Convert Date to a number rather than string to make it actually useful for once

In [39]:
def convert_time(df):

    df['sunset'] = pd.to_datetime(df['sunset'], errors='coerce').dt.hour * 3600 + \
                pd.to_datetime(df['sunset'], errors='coerce').dt.minute * 60 + \
                pd.to_datetime(df['sunset'], errors='coerce').dt.second

    df['sunrise'] = pd.to_datetime(df['sunrise'], errors='coerce').dt.hour * 3600 + \
                pd.to_datetime(df['sunrise'], errors='coerce').dt.minute * 60 + \
                pd.to_datetime(df['sunrise'], errors='coerce').dt.second
    
    return df

Replace Missing Values

In [40]:
df.apply(pd.isnull).sum()/df.shape[0]

name                0.000000
datetime            0.000000
tempmax             0.000000
tempmin             0.000000
temp                0.000000
feelslikemax        0.000000
feelslikemin        0.000000
feelslike           0.000000
dew                 0.000000
humidity            0.000000
precip              0.194878
precipprob          0.000000
precipcover         0.000000
windspeed           0.000000
winddir             0.003255
sealevelpressure    0.030599
cloudcover          0.000000
visibility          0.000326
solarradiation      0.392687
solarenergy         0.392687
uvindex             0.392687
sunrise             0.000000
sunset              0.000000
moonphase           0.000000
conditions          0.000000
description         0.000000
icon                0.000000
stations            0.000000
dtype: float64

In [41]:
df["precip"].value_counts() / df.shape[0]

precip
0.000    0.346463
0.039    0.027018
0.079    0.023980
0.012    0.022569
0.004    0.021050
           ...
0.239    0.000109
0.400    0.000109
0.160    0.000109
0.195    0.000109
0.732    0.000109
Name: count, Length: 659, dtype: float64

In [42]:
def drop_unnecessary_columns(df):
    """
    Drops unnecessary columns from the DataFrame.
    """
    columns_to_drop = ['icon', 'stations', 'description', 'conditions','precipprob', 'uvindex', 'moonphase']
    df.drop(columns=columns_to_drop, inplace=True, errors='ignore')  # Use errors='ignore' to avoid KeyError if column doesn't exist
    return df



df.head(10)

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarradiation,solarenergy,uvindex,sunrise,sunset,moonphase,conditions,description,icon,stations
0,"Chaguanas, Trinidad, Trinidad And Tobago",01/01/2000,87.9,71.7,80.0,94.4,71.7,82.7,72.0,78.0,...,NaN,NaN,NaN,2000-01-01T06:23:33,2000-01-01T17:54:34,0.83,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
1,"Chaguanas, Trinidad, Trinidad And Tobago",02/01/2000,87.9,71.3,78.2,96.1,71.3,80.5,72.5,83.7,...,NaN,NaN,NaN,2000-01-02T06:23:56,2000-01-02T17:55:07,0.86,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
2,"Chaguanas, Trinidad, Trinidad And Tobago",03/01/2000,89.7,73.5,79.3,95.0,73.5,81.2,71.6,78.6,...,NaN,NaN,NaN,2000-01-03T06:24:20,2000-01-03T17:55:40,0.90,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
3,"Chaguanas, Trinidad, Trinidad And Tobago",04/01/2000,84.3,71.3,76.1,89.8,71.3,77.2,70.9,84.9,...,NaN,NaN,NaN,2000-01-04T06:24:42,2000-01-04T17:56:12,0.93,Partially cloudy,Clearing in the afternoon.,partly-cloudy-day,78970099999
4,"Chaguanas, Trinidad, Trinidad And Tobago",05/01/2000,81.2,73.1,76.1,86.7,73.1,76.5,73.9,93.0,...,NaN,NaN,NaN,2000-01-05T06:25:04,2000-01-05T17:56:45,0.96,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
5,"Chaguanas, Trinidad, Trinidad And Tobago",06/01/2000,87.9,73.5,77.9,96.1,73.5,79.7,73.4,86.7,...,NaN,NaN,NaN,2000-01-06T06:25:25,2000-01-06T17:57:18,0.00,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
6,"Chaguanas, Trinidad, Trinidad And Tobago",07/01/2000,87.5,73.5,77.3,92.9,73.5,78.4,71.5,83.4,...,NaN,NaN,NaN,2000-01-07T06:25:45,2000-01-07T17:57:50,0.03,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
7,"Chaguanas, Trinidad, Trinidad And Tobago",08/01/2000,87.9,72.8,79.7,92.9,72.8,81.6,70.6,75.8,...,NaN,NaN,NaN,2000-01-08T06:26:04,2000-01-08T17:58:22,0.07,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
8,"Chaguanas, Trinidad, Trinidad And Tobago",09/01/2000,87.9,71.7,78.5,95.4,71.7,81.3,72.3,82.3,...,NaN,NaN,NaN,2000-01-09T06:26:23,2000-01-09T17:58:55,0.10,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
9,"Chaguanas, Trinidad, Trinidad And Tobago",10/01/2000,88.4,73.5,79.6,95.7,73.5,82.0,71.9,78.8,...,NaN,NaN,NaN,2000-01-10T06:26:40,2000-01-10T17:59:27,0.14,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999

Convert rain to mm

In [43]:
def backfill_missing_rain(df):

    df["datetime"] = pd.to_datetime(df["datetime"], format='mixed' ,dayfirst=True)   #concert date to a datetime object
    df["day"] = df["datetime"].dt.day
    df["month"] = df["datetime"].dt.month
    df["year"] = df["datetime"].dt.year
    ref_df = df.loc['01/0/2005':'31/12/2025']

    day_avg_precip = (ref_df[ref_df['precip'].notna()].groupby(['month', 'day'])['precip'].mean())
    missing_mask = (df.year <= 2004) & (df['precip'].isna())
    df.loc[missing_mask, 'precip'] = df[missing_mask].apply(lambda row: day_avg_precip.get((row['month'], row['day']), None),axis=1)

    df.drop(columns=['precipprob'], inplace=True)
   
    return df

In [44]:
def inches_to_mm(inches):
    return inches * 25.4


def convert_inches_to_mm(df):
    df['precip'] = df['precip'].apply(lambda x: pd.Series(inches_to_mm(x)))
    df.rename(columns={"windspeed": "windspeed mph"})

    return df

df.head(10)

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarradiation,solarenergy,uvindex,sunrise,sunset,moonphase,conditions,description,icon,stations
0,"Chaguanas, Trinidad, Trinidad And Tobago",01/01/2000,87.9,71.7,80.0,94.4,71.7,82.7,72.0,78.0,...,NaN,NaN,NaN,2000-01-01T06:23:33,2000-01-01T17:54:34,0.83,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
1,"Chaguanas, Trinidad, Trinidad And Tobago",02/01/2000,87.9,71.3,78.2,96.1,71.3,80.5,72.5,83.7,...,NaN,NaN,NaN,2000-01-02T06:23:56,2000-01-02T17:55:07,0.86,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
2,"Chaguanas, Trinidad, Trinidad And Tobago",03/01/2000,89.7,73.5,79.3,95.0,73.5,81.2,71.6,78.6,...,NaN,NaN,NaN,2000-01-03T06:24:20,2000-01-03T17:55:40,0.90,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
3,"Chaguanas, Trinidad, Trinidad And Tobago",04/01/2000,84.3,71.3,76.1,89.8,71.3,77.2,70.9,84.9,...,NaN,NaN,NaN,2000-01-04T06:24:42,2000-01-04T17:56:12,0.93,Partially cloudy,Clearing in the afternoon.,partly-cloudy-day,78970099999
4,"Chaguanas, Trinidad, Trinidad And Tobago",05/01/2000,81.2,73.1,76.1,86.7,73.1,76.5,73.9,93.0,...,NaN,NaN,NaN,2000-01-05T06:25:04,2000-01-05T17:56:45,0.96,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
5,"Chaguanas, Trinidad, Trinidad And Tobago",06/01/2000,87.9,73.5,77.9,96.1,73.5,79.7,73.4,86.7,...,NaN,NaN,NaN,2000-01-06T06:25:25,2000-01-06T17:57:18,0.00,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
6,"Chaguanas, Trinidad, Trinidad And Tobago",07/01/2000,87.5,73.5,77.3,92.9,73.5,78.4,71.5,83.4,...,NaN,NaN,NaN,2000-01-07T06:25:45,2000-01-07T17:57:50,0.03,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
7,"Chaguanas, Trinidad, Trinidad And Tobago",08/01/2000,87.9,72.8,79.7,92.9,72.8,81.6,70.6,75.8,...,NaN,NaN,NaN,2000-01-08T06:26:04,2000-01-08T17:58:22,0.07,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
8,"Chaguanas, Trinidad, Trinidad And Tobago",09/01/2000,87.9,71.7,78.5,95.4,71.7,81.3,72.3,82.3,...,NaN,NaN,NaN,2000-01-09T06:26:23,2000-01-09T17:58:55,0.10,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
9,"Chaguanas, Trinidad, Trinidad And Tobago",10/01/2000,88.4,73.5,79.6,95.7,73.5,82.0,71.9,78.8,...,NaN,NaN,NaN,2000-01-10T06:26:40,2000-01-10T17:59:27,0.14,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999

Convert Degrees

In [45]:
def fahrenheit_to_celsius(fahrenheit):
    celsius = (fahrenheit - 32) * 5 / 9
    return round(celsius, 1)

def convert_temperatures(df):

    df[[ 'tempmax c']] = df ['tempmax'].apply(lambda x: pd.Series(fahrenheit_to_celsius(x)))
    df[[ 'tempmin c']] = df ['tempmin'].apply(lambda x: pd.Series(fahrenheit_to_celsius(x)))
    df[[ 'avgtemp c']] = df ['temp'].apply(lambda x: pd.Series(fahrenheit_to_celsius(x)))

    df[[ 'feelslikemax c']] = df ['feelslikemax'].apply(lambda x: pd.Series(fahrenheit_to_celsius(x)))
    df[[ 'feelslikemin c']] = df ['feelslikemin'].apply(lambda x: pd.Series(fahrenheit_to_celsius(x)))
    df[[ 'avgfeelsliketemp c']] = df ['feelslike'].apply(lambda x: pd.Series(fahrenheit_to_celsius(x)))

    df[[ 'dewpoint c']] = df ['dew'].apply(lambda x: pd.Series(fahrenheit_to_celsius(x)))

    df.drop(columns=['temp'],inplace=True)
    df.drop(columns=['tempmax'],inplace=True)
    df.drop(columns=['tempmin'],inplace=True)

    df.drop(columns=['feelslike'],inplace=True)
    df.drop(columns=['feelslikemax'],inplace=True)
    df.drop(columns=['feelslikemin'],inplace=True)
    df.drop(columns=['dew'],inplace=True)

    return df

df.head(10)

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarradiation,solarenergy,uvindex,sunrise,sunset,moonphase,conditions,description,icon,stations
0,"Chaguanas, Trinidad, Trinidad And Tobago",01/01/2000,87.9,71.7,80.0,94.4,71.7,82.7,72.0,78.0,...,NaN,NaN,NaN,2000-01-01T06:23:33,2000-01-01T17:54:34,0.83,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
1,"Chaguanas, Trinidad, Trinidad And Tobago",02/01/2000,87.9,71.3,78.2,96.1,71.3,80.5,72.5,83.7,...,NaN,NaN,NaN,2000-01-02T06:23:56,2000-01-02T17:55:07,0.86,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
2,"Chaguanas, Trinidad, Trinidad And Tobago",03/01/2000,89.7,73.5,79.3,95.0,73.5,81.2,71.6,78.6,...,NaN,NaN,NaN,2000-01-03T06:24:20,2000-01-03T17:55:40,0.90,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
3,"Chaguanas, Trinidad, Trinidad And Tobago",04/01/2000,84.3,71.3,76.1,89.8,71.3,77.2,70.9,84.9,...,NaN,NaN,NaN,2000-01-04T06:24:42,2000-01-04T17:56:12,0.93,Partially cloudy,Clearing in the afternoon.,partly-cloudy-day,78970099999
4,"Chaguanas, Trinidad, Trinidad And Tobago",05/01/2000,81.2,73.1,76.1,86.7,73.1,76.5,73.9,93.0,...,NaN,NaN,NaN,2000-01-05T06:25:04,2000-01-05T17:56:45,0.96,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
5,"Chaguanas, Trinidad, Trinidad And Tobago",06/01/2000,87.9,73.5,77.9,96.1,73.5,79.7,73.4,86.7,...,NaN,NaN,NaN,2000-01-06T06:25:25,2000-01-06T17:57:18,0.00,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
6,"Chaguanas, Trinidad, Trinidad And Tobago",07/01/2000,87.5,73.5,77.3,92.9,73.5,78.4,71.5,83.4,...,NaN,NaN,NaN,2000-01-07T06:25:45,2000-01-07T17:57:50,0.03,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
7,"Chaguanas, Trinidad, Trinidad And Tobago",08/01/2000,87.9,72.8,79.7,92.9,72.8,81.6,70.6,75.8,...,NaN,NaN,NaN,2000-01-08T06:26:04,2000-01-08T17:58:22,0.07,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
8,"Chaguanas, Trinidad, Trinidad And Tobago",09/01/2000,87.9,71.7,78.5,95.4,71.7,81.3,72.3,82.3,...,NaN,NaN,NaN,2000-01-09T06:26:23,2000-01-09T17:58:55,0.10,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999
9,"Chaguanas, Trinidad, Trinidad And Tobago",10/01/2000,88.4,73.5,79.6,95.7,73.5,82.0,71.9,78.8,...,NaN,NaN,NaN,2000-01-10T06:26:40,2000-01-10T17:59:27,0.14,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,78970099999

In [46]:
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)  # Ignore FutureWarnings

def fill_missing_values(df):
    """
    Fill missing values in the DataFrame.
    """
    df = df.fillna(method="ffill")

    return df

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9216 entries, 0 to 9215
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              9216 non-null   object
 1   datetime          9216 non-null   object
 2   tempmax           9216 non-null   float64
 3   tempmin           9216 non-null   float64
 4   temp              9216 non-null   float64
 5   feelslikemax      9216 non-null   float64
 6   feelslikemin      9216 non-null   float64
 7   feelslike         9216 non-null   float64
 8   dew               9216 non-null   float64
 9   humidity          9216 non-null   float64
 10  precip            7420 non-null   float64
 11  precipprob        9216 non-null   int64
 12  precipcover       9216 non-null   float64
 13  windspeed         9216 non-null   float64
 14  winddir           9186 non-null   float64
 15  sealevelpressure  8934 non-null   float64
 16  cloudcover        9216 non-null   float64
 17  visibility        9213 non-null   float64
 18  solarradiation    5597 non-null   float64
 19  solarenergy       5597 non-null   float64
 20  uvindex           5597 non-null   float64
 21  sunrise           9216 non-null   object
 22  sunset            9216 non-null   object
 23  moonphase         9216 non-null   float64
 24  conditions        9216 non-null   object
 25  description       9216 non-null   object
 26  icon              9216 non-null   object
 27  stations          9216 non-null   object
dtypes: float64(19), int64(1), object(8)
memory usage: 2.0+ MB

In [48]:
for col in df.columns:
    print(col,df[col].nunique())

name 1
datetime 9216
tempmax 143
tempmin 107
temp 123
feelslikemax 303
feelslikemin 121
feelslike 220
dew 149
humidity 342
precip 659
precipprob 2
precipcover 25
windspeed 133
winddir 1202
sealevelpressure 102
cloudcover 716
visibility 102
solarradiation 1981
solarenergy 241
uvindex 11
sunrise 9216
sunset 9216
moonphase 96
conditions 5
description 32
icon 5
stations 19

In [49]:
df.isna().sum()

name                   0
datetime               0
tempmax                0
tempmin                0
temp                   0
feelslikemax           0
feelslikemin           0
feelslike              0
dew                    0
humidity               0
precip              1796
precipprob             0
precipcover            0
windspeed              0
winddir               30
sealevelpressure     282
cloudcover             0
visibility             3
solarradiation      3619
solarenergy         3619
uvindex             3619
sunrise                0
sunset                 0
moonphase              0
conditions             0
description            0
icon                   0
stations               0
dtype: int64

# Outlier Temprature Analysis
Max Temp Ever Recorded in Triniad : 37.8
Lowest Temp Ever Recorded in Trinidad : 16.1

https://www.metoffice.gov.tt/Climate#:~:text=The%20coolest%20minimum%20temperature%20is,and%2030th%2C%201964%20at%20Piarco.

Backfill null values with avg for that day to avoid squewing data

In [50]:
def backfill_solar_energy(df):
    

    # Calculate daily average solar energy using data from 2010 and after
    day_avg_solarenergy = df[df['year'] >= 2010].groupby(['month', 'day'])['solarenergy'].mean()

    # Mask: rows where solarenergy is null AND year is before 2010
    mask = df['solarenergy'].isna() & (df['year'] < 2010)

    # Replace those values with the daily average from 2010 and after
    df.loc[mask, 'solarenergy'] = df[mask].apply(
        lambda row: day_avg_solarenergy.get((row['month'], row['day']), row['solarenergy']),
        axis=1
    )

    return df

In [51]:
def backfill_solarradiation(df):
    
    """
    Fill missing solar radiation values using daily averages from 2010 and after.
    """

    # Calculate daily average solar energy using data from 2010 and after
    day_avg_solarradiation = df[df['year'] >= 2010].groupby(['month', 'day'])['solarradiation'].mean()

    # Mask: rows where solarenergy is null AND year is before 2010
    mask = df['solarradiation'].isna() & (df['year'] < 2010)

    # Replace those values with the daily average from 2010 and after
    df.loc[mask, 'solarradiation'] = df[mask].apply(
        lambda row: day_avg_solarradiation.get((row['month'], row['day']), row['solarradiation']),
        axis=1
    )
    return df

Replace outliers with more than 36C actual temp with average for that day

In [52]:
def fix_max_temps(df):
    """
    Fix maximum temperatures that are above 37.8 degrees Celsius.
    Replace them with the average maximum temperature for that day across all years.
    """

    # Calculate daily average max temperature for days where tempmax c <= 37.8

    day_avg_tempmax = df[df['tempmax c'] <= 37.8].groupby(['month', 'day'])['tempmax c'].mean()

    mask = df['tempmax c'] > 37.8

    df.loc[mask, 'tempmax c'] = df[mask].apply(
        lambda row: day_avg_tempmax.get((row['month'], row['day']), row['tempmax c']),
        axis=1
    )

    return df

Replace outlier mintemp < 16.1 with average for that day

In [53]:
def fix_min_temps(df):
    """
    Fix minimum temperatures that are below 16.1 degrees Celsius.
    Replace them with the average minimum temperature for that day across all years.
    """

    # Calculate daily average min temperature for days where tempmin c >= 16.1  

    day_avg_tempmin = df[df['tempmin c'] >= 16.1].groupby(['month', 'day'])['tempmin c'].mean()

    mask = df['tempmin c'] < 16.1

    df.loc[mask, 'tempmin c'] = df[mask].apply(
        lambda row: day_avg_tempmin.get((row['month'], row['day']), row['tempmin c']),
        axis=1
    )

    return df

# Replace outlier feelsmintemp < 16.1 with average for that day

In [54]:
def fix_feelslike_max(df):
    """
    Fix maximum feels-like temperatures that are above 37.8 degrees Celsius.
    Replace them with the average maximum feels-like temperature for that day across all years.
    """


    day_avg_tempminfeellike = df[df['feelslikemin c'] >= 16.1].groupby(['month', 'day'])['feelslikemin c'].mean()

    mask = df['feelslikemin c'] < 16.1

    df.loc[mask, 'feelslikemin c'] = df[mask].apply(
        lambda row: day_avg_tempminfeellike.get((row['month'], row['day']), row['feelslikemin c']),
        axis=1
    )
    df.drop(columns=['month', 'day', 'year'], inplace=True)

    return df

In [55]:

# Ensure 'datetime' column is a datetime type

def convert_datetime(df):
    """
    Convert the 'datetime' column to a datetime type and filter out rows before 2005.
    """
    
    # Convert 'datetime' column to datetime type
    df['datetime'] = pd.to_datetime(df['datetime'], errors='coerce')

    # Filter out rows before 2005
    df = df[df['datetime'] >= '2005-01-01']

    return df

In [56]:
def rename_all_columns():
    df['name'] = df['name'].apply(lambda x: x.split(',')[0].strip())
    location = df['name'].iloc[0]

    return location


def save_cleaned_data(df):

    # Run function and save cleaned file
    location = rename_all_columns()

    path ='Refined Datasets/'   # Define the path where the cleaned file will be saved
    oldfname = f'{path} {location} cleaned.csv'  # Check if the old file exists and remove it

    if os.path.exists(oldfname):
        os.remove(oldfname)   # Remove the old file if it exists

    fname = f'{path}{location} cleaned.csv'    #Append the location to the filename
    print(f"Saving cleaned {location} data to {path}")  
    df.to_csv(fname, index=False)   # Save the cleaned DataFrame to a CSV file
    print(f"Cleaned data saved to {fname}")   # Print a message indicating where the cleaned data is saved

In [ ]:
location_csvs = []
refined_datasets_path = 'Refined Datasets/'  # Define the path for refined datasets
refined_datasets = []

# Create a report file to log the CSV files found in the directory
if not os.path.exists('Refined Datasets/report.txt'):
    report_file = open('Refined Datasets/report.txt', 'x')
else:
    report_file = open('Refined Datasets/report.txt', 'w')


report_file.write("Report of CSV files found in the directory:\n")


# Walk through the directory and collect all CSV files

for dirname, _, filenames in os.walk('AllData/Merged Location Csvs'):
    for filename in filenames:
        if filename.endswith('.csv'):
            location_csvs.append((dirname, filename))

            print(os.path.join(dirname, filename))

print(f"Found {len(location_csvs)} CSV files in the directory.")


for location in location_csvs:
    print(f"Processing {location[1]} in {location[0]}")
    df = pd.read_csv(os.path.join(location[0], location[1]), encoding='latin-1', skip_blank_lines=True)  # Load the dataset
    pd.options.mode.copy_on_write = True  # Set copy_on_write to True to avoid SettingWithCopyWarning

    df = convert_date(df)
    df = convert_time(df)
    df = backfill_missing_rain(df)
    df = convert_inches_to_mm(df)
    df = convert_temperatures(df)
    df = fill_missing_values(df)
    df = backfill_solar_energy(df)
    df = backfill_solarradiation(df)
    df = fix_max_temps(df)
    df = fix_min_temps(df)
    df = fix_feelslike_max(df)
    df = convert_datetime(df)
    df = drop_unnecessary_columns(df)


    save_cleaned_data(df)  # Save the cleaned DataFrame to a CSV file
    refined_datasets.append(df)  # Append the cleaned DataFrame to the list of refined datasets

    print(f"Finished processing {location[1]} in {location[0]}")
    report_file.write(f"Processed {location[1]} in {location[0]}\n")  # Log the processed file in the report
    df_report= df.isna().sum()
    report_file.write(f"Missing values report:\n{df_report}\n")  # Log the missing values report in the report file
    report_file.write("------------------------------------------------\n")  # Add a newline for better readability in the report file



report_file.close()  # Close the report file after processing all CSV files
print("All CSV files processed and report generated.")

AllData/VisualCrossing/LocationCsvs\Arima_weather_data_2000_2025.csv
AllData/VisualCrossing/LocationCsvs\Chaguanas_weather_data_2000_2025.csv
AllData/VisualCrossing/LocationCsvs\Couva-Tabaquite-Talparo_weather_data_2000_2025.csv
AllData/VisualCrossing/LocationCsvs\Crown Point_weather_data_2000_2025.csv
AllData/VisualCrossing/LocationCsvs\Diego Martin_weather_data_2000_2025.csv
AllData/VisualCrossing/LocationCsvs\Penal-Debe_weather_data_2000_2025.csv
AllData/VisualCrossing/LocationCsvs\Point Fortin_weather_data_2000_2025.csv
AllData/VisualCrossing/LocationCsvs\Port Of Spain_weather_data_2000_2025.csv
AllData/VisualCrossing/LocationCsvs\Princes Town_weather_data_2000_2025.csv
AllData/VisualCrossing/LocationCsvs\Rio Claro-Mayaro_weather_data_2000_2025.csv
AllData/VisualCrossing/LocationCsvs\San Fernando_weather_data_2000_2025.csv
AllData/VisualCrossing/LocationCsvs\San Juan-Laventille_weather_data_2000_2025.csv
AllData/VisualCrossing/LocationCsvs\Sangre Grande_weather_data_2000_2025.csv
AllData/VisualCrossing/LocationCsvs\Scarborough_weather_data_2000_2025.csv
AllData/VisualCrossing/LocationCsvs\Siparia_weather_data_2000_2025.csv
AllData/VisualCrossing/LocationCsvs\Tunapuna-Piarco_weather_data_2000_2025.csv
Found 16 CSV files in the directory.
Processing Arima_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Saving cleaned Arima data to Refined Datasets/
Cleaned data saved to Refined Datasets/Arima cleaned.csv
Finished processing Arima_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Processing Chaguanas_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Saving cleaned Chaguanas data to Refined Datasets/
Cleaned data saved to Refined Datasets/Chaguanas cleaned.csv
Finished processing Chaguanas_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Processing Couva-Tabaquite-Talparo_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Saving cleaned Couva-Tabaquite-Taiparo data to Refined Datasets/
Cleaned data saved to Refined Datasets/Couva-Tabaquite-Taiparo cleaned.csv
Finished processing Couva-Tabaquite-Talparo_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Processing Crown Point_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Saving cleaned Crown Point data to Refined Datasets/
Cleaned data saved to Refined Datasets/Crown Point cleaned.csv
Finished processing Crown Point_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Processing Diego Martin_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Saving cleaned Diego Martin data to Refined Datasets/
Cleaned data saved to Refined Datasets/Diego Martin cleaned.csv
Finished processing Diego Martin_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Processing Penal-Debe_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Saving cleaned Penal-Debe data to Refined Datasets/
Cleaned data saved to Refined Datasets/Penal-Debe cleaned.csv
Finished processing Penal-Debe_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Processing Point Fortin_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Saving cleaned Point Fortin data to Refined Datasets/
Cleaned data saved to Refined Datasets/Point Fortin cleaned.csv
Finished processing Point Fortin_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Processing Port Of Spain_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Saving cleaned Port of Spain data to Refined Datasets/
Cleaned data saved to Refined Datasets/Port of Spain cleaned.csv
Finished processing Port Of Spain_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Processing Princes Town_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Saving cleaned Princes Town data to Refined Datasets/
Cleaned data saved to Refined Datasets/Princes Town cleaned.csv
Finished processing Princes Town_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Processing Rio Claro-Mayaro_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Saving cleaned Rio Claro-Mayaro data to Refined Datasets/
Cleaned data saved to Refined Datasets/Rio Claro-Mayaro cleaned.csv
Finished processing Rio Claro-Mayaro_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Processing San Fernando_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Saving cleaned San Fernando data to Refined Datasets/
Cleaned data saved to Refined Datasets/San Fernando cleaned.csv
Finished processing San Fernando_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Processing San Juan-Laventille_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Saving cleaned San Juan-Laventille data to Refined Datasets/
Cleaned data saved to Refined Datasets/San Juan-Laventille cleaned.csv
Finished processing San Juan-Laventille_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Processing Sangre Grande_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Saving cleaned Sangre Grande data to Refined Datasets/
Cleaned data saved to Refined Datasets/Sangre Grande cleaned.csv
Finished processing Sangre Grande_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Processing Scarborough_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Saving cleaned Scarborough data to Refined Datasets/
Cleaned data saved to Refined Datasets/Scarborough cleaned.csv
Finished processing Scarborough_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Processing Siparia_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Saving cleaned Siparia data to Refined Datasets/
Cleaned data saved to Refined Datasets/Siparia cleaned.csv
Finished processing Siparia_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Processing Tunapuna-Piarco_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
Saving cleaned Piarco data to Refined Datasets/
Cleaned data saved to Refined Datasets/Piarco cleaned.csv
Finished processing Tunapuna-Piarco_weather_data_2000_2025.csv in AllData/VisualCrossing/LocationCsvs
All CSV files processed and report generated.

In [58]:
#concat all the cleaned data into one file

df = pd.concat(refined_datasets, ignore_index=True)  # Concatenate all cleaned DataFrames into one
df.to_csv('Refined Datasets/All_Cleaned_Data.csv', index=False)
print("All cleaned data concatenated and saved to 'Refined Datasets/All_Cleaned_Data.csv'.")

All cleaned data concatenated and saved to 'Refined Datasets/All_Cleaned_Data.csv'.